name: qr_code_dart_scan
description: A QR code scanner that works on both iOS and Android using dart decoder.
version: 0.4.0
homepage: https://github.com/RafaelBarbosatec/qr_code_dart_scan

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.9.4+18
  zxing_lib: ^0.6.0
  image: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: