name: qr_code_dart_scan
description: A QR code scanner that works on both iOS and Android using dart decoder.
version: 0.2.0
homepage: https://github.com/RafaelBarbosatec/qr_code_dart_scan

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.9.4+1
  zxing_lib: 0.5.0
  image: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: